# Name
NAME_MAX_LENGTH = 150
NAME_MIN_LENGTH = 2

# Description / Bio
DESCRIPTION_MAX_LENGTH = 4000
DESCRIPTION_MIN_LENGTH = 2

# Image URL
IMAGE_URL_MAX_LENGTH = 500
IMAGE_URL_MIN_LENGTH = 10

# Studio contact info
PHONE_MAX_LENGTH = 20
EMAIL_MAX_LENGTH = 255

# Booking
BOOKING_HORIZON_DAYS = 28

# Price plan
PRICE_SUBTITLE_MAX_LENGTH = 100
OPTION_TEXT_MAX_LENGTH = 200
