# Style
STYLE_NAME_MAX_LENGTH = 100
STYLE_NAME_MIN_LENGTH = 2
STYLE_DESCRIPTION_MAX_LENGTH = 4000
STYLE_DESCRIPTION_MIN_LENGTH = 2

# StyleImage
STYLE_IMAGE_URL_MAX_LENGTH = 500
STYLE_IMAGE_URL_MIN_LENGTH = 10
